### PR TITLE
Created HighestPoints unit test

### PR DESCRIPTION
**Pull request by dhagens**
@mfunk, please review and merge.

### CODE REVIEW

**Comment by mfunk** [comment]
Hey @dhagens I'll be checking this one out tomorrow morning. But could you do a pull from 'dev' as I've updated that branch from a PR @jmccausland did earlier today.

**Comment by dhagens** [comment]
My branch has been merged from dev.  The conflicts were resolved and the changes were added, but I'm seeing comments like this in the updated file - >>>>>>> refs/remotes/origin/dev  They are in VisibilityTestSuite.py.  I've not resolved conflicts through Git Shell before so I'm not sure if this is expected or not.

**Comment by jmccausland** [comment]
you need to manually merge the VisibilityTestSuite.py file since it changed after you created your branch and you also made changes

The comments you see are showing you what you have and what is on dev.  Review those two in each commented section and modify if needed.  Most of the time you just need to remove the comments and you're fine.

**Comment by dhagens** [comment]
Thanks.  The file has been updated with the comments removed.

**Comment by mfunk** [comment]
Thanks @dhagens, I'll check it out in a bit.

**Pull request merged**
