### PR TITLE
Updated LLOS doc for ArcMap tools

### PR DESCRIPTION
**Pull request by mfunk**
Addresses using Attribute window in Editor to modify "Height above
surface" attribute for Observer/Target feature sets.

### CODE REVIEW

**Comment by topowright** [comment]
@mfunk I cannot merge this pull request because you have conflicts.

**Comment by csmoore** [comment]
Probably as a result of this PR having changed the same binary file ( Military_Tools_10.3.tbx ) : https://github.com/Esri/military-tools-geoprocessing-toolbox/pull/31 . 

This is a case of 2 people simultaneous editing a tbx or model or other binary file (not something any version control system can really reliably handle)

**Comment by mfunk** [comment]
Closing this PR. Will do another fetch/merge, update again with a new PR.

**Comment by mfunk** [comment]
Though we will want ALL other PRs either merged or rejected before that. As there will ALWAYS be conflicts between TBX files.

**Pull request closed without merging**
