### PR TITLE
#401 Add check that points fall within surface

### PR DESCRIPTION
**Pull request by csmoore**
See Issue: #401 - Adds check that input points fall within surface before proceeding

### CODE REVIEW

**Comment by BobBooth** [comment]
@csmoore  LLOS is correctly checking to see if the input Observer points are within the surface and handling the case where they are not. 
image

However, it is not checking to see if the Target points are within the surface, and it is still crashing if the Observer is on the surface but the target is not.
image

**Comment by BobBooth** [comment]
RLOS does not crash Pro, but the error message could be clearer, that the problem was the single Observer point was outside of the surface.
image

RLOS works with multiple points when some are on and some are off the surface. It would be nice if it reported that some of the points were outside of the surface.  Only warning in GP results was about coordinate system mismatch.
image

**Comment by BobBooth** [comment]
LLOS also crashes Pro where some Observers are on and some are off, and some Targets are on and some are off.
image

**Comment by csmoore** [comment]
@BobBooth - looks like you are getting some unexpected behavior:

1. LLOS - it is supposed to be checking the targets so not sure why that isn't happening
2. RLOS - it is failing to register that the one point is outside the surface 

You might have to step me through these cases since I'm not able to repro:

image

**Comment by BobBooth** [comment]
@csmoore - I just tried RLOS again and I am seeing the correct behavior now.

Not sure what was up with that.
Will retest LLOS now.

**Comment by BobBooth** [comment]
@csmoore - Now LLOS seems to be working correctly for me.
 I had cloned the repo from your branch, and I had the latest .py files but I think there were old version of the compiled python scripts in military-tools-geoprocessing-toolbox\tools\militarytools\esri\toolboxes\scripts\__pycache__
I deleted those and re-ran, and now it is working correctly.

**Pull request merged**
