### PR TITLE
Changed layer names to industry standard

### PR DESCRIPTION
**Pull request by kgonzago**
Change output layer names to match industry standards
## Description

1. FullWedge is now Range
2. Wedge if now Field of View
3. viewshed is now Viewshed
## Related Issue

Addresses #264 

## Motivation and Context

fullwedge and wedge is confusing and no meaning in the industry. 

## How Has This Been Tested?

ArcGIS Pro and ArcMap

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by kgonzago** [comment]
@topowright 
1. can you provide the new sequential order of the input parameters for this tool?
2. You stated symbology should match RLOS. Which layer symbology are you referring to and to which layer (Range or Field of View)

**Comment by kgonzago** [comment]
@topowright 
1. Order of input parameter addressed
2. Symbology to mimic RLOS already addressed. Please look at [line 539](https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/116beac1d7d17d10e66806641e3c955f32c3ae3d/toolboxes/scripts/VisTools.py#L539) in the `Radial Line of Sight and Range` tool and [line 822](https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/116beac1d7d17d10e66806641e3c955f32c3ae3d/toolboxes/scripts/VisTools.py#L822) in the `RLOS` tool. Both reference the same layer file.
3. Camel casing for `Field of View` fixed. I used `_` since `spaces` are illegal characters.

**Comment by topowright** [comment]
I tried to verify this issue, but found that the near distance repeats itself: 
image

**Comment by kgonzago** [comment]
@topowright Good catch. Fixed and ready for review.

**Comment by ACueva** [comment]
Verified directly from kg/#264.

**Pull request merged**
