### PR TITLE
Updated/add tool documentation for Visibility toolset and Distance and Direction toolset

### PR DESCRIPTION
**Pull request by dfoll**
## Description
Made changes to tool help for all three tools in the Distance and Direction toolset. Added new tool help to the new script tools in the Visibility toolset.

## Related Issue
#147 #161 #162 #144 #145 #148 #149 #154 #155 #156 

## Motivation and Context
Improves tool help

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

updated/added tool documentation for distance and direction toolset, and visibility toolset

### CODE REVIEW

**Comment by dfoll** [comment]
@mfunk since you are still scripting some of these tools, and only one of us can touch this at a time, i would politely request, that have a look at the tool help changes I have done for visibility, just to make sure you are still ok with everything i did

**Comment by mfunk** [comment]
Got it. Will start looking at this sometime this afternoon or tomorrow.

**Comment by mfunk** [comment]
@dfoll  Got a problem. Did you use a version newer than 10.3.1 to do the doc changes? I am not able to see the script tools in the toolbox....

image

**Comment by dfoll** [comment]
@mfunk if there is a problem, yo i'll solve it 
vanilla-ice

**Pull request merged**
