### PR TITLE
Added LLOS and RLOS Unit tests.

### PR DESCRIPTION
**Pull request by dhagens**
Added LLOS and RLOS Unit tests.   Updated Lowest Points model to use
scratchGdb.  Added test data for LLOS for ArcMap

@mfunk, please review and merge

### CODE REVIEW

**Comment by mfunk** [comment]
@dhagens 
hehehehe.... you got some extra baggage :)
there are a few **MTGT....log** files that need to be scrubbed before I can merge.

**Comment by csmoore** [comment]
And/or a .gitignore that needs updated?

**Comment by mfunk** [comment]
@csmoore To ignore all '*.log' files? Or to ignore all 'MTGT*.log' files?

**Comment by mfunk** [comment]
Going to have to hold on this one @dhagens. I'm seeing some corruption in the **MilitaryToolsTestData.gdb** where the new LLOS point features are showing up as tables only. None of it is allowing me to merge. :(

We will have to sort this out manually on Monday

**Comment by csmoore** [comment]
@mfunk - `*.log` should work and not ignore any valid files

**Comment by mfunk** [comment]
handled the log file/log folder in #80

**Pull request merged**
