### PR TITLE
update to Desktop LLOS

### PR DESCRIPTION
**Pull request by mfunk**
update to Desktop LLOS

### CODE REVIEW

**Comment by mfunk** [comment]
@topowright  Got the LLOS stuff updated. However got more Model Builder Issues... again.

**Comment by topowright** [comment]
@mfunk I see the results, but no labels on the end targets. Did you get the labels to work?

**Comment by topowright** [comment]
@mfunk I am not able to get the labels to show up on the end targets. I also, get an error if I run the tool more than once. the error is: 

Running script AttachProfileGraphToLLOS...
Found 15 unique sight line IDs ...
Building graphs for lines ...
Building graph from observer 1 to target 1 ...
PYTHON ERRORS:
Traceback info:
  File "C:\Users\lyle6003\Documents\GitHub\military-tools-geoprocessing-toolbox\toolboxes\scripts\LLOSProfileGraphAttachments.py", line 164, in <module>
    pylab.savefig(graphPath, dpi=900)

Error Info:
main thread is not in main loop
ArcPy ERRORS:
Executing: CalculateField C:\Users\lyle6003\Documents\ArcGIS\Projects\MyProject22\MyProject22.gdb\surfaceLines1 pngname ""profile" + str(!SourceOID!)" PYTHON #
Start Time: Monday, June 20, 2016 6:40:06 PM
Succeeded at Monday, June 20, 2016 6:40:06 PM (Elapsed Time: 0.09 seconds)
Completed script AttachProfileGraphToLLOS...
Failed to execute (Attach Profile Graph To LLOS).
Failed at Monday, June 20, 2016 6:40:10 PM (Elapsed Time: 4.53 seconds)
Failed to execute (LinearLineOfSight).
Failed at Monday, June 20, 2016 6:40:11 PM (Elapsed Time: 16.23 seconds)

**Comment by topowright** [comment]
Spoke with @mfunk and identified that the no labels were an issue.

**Pull request merged**
