### PR TITLE
Addresses #366

### PR DESCRIPTION
**Pull request by kgonzago**
This fix addresses #366 

## Description

Input point needs to be projected to Web Mercator in order for the tool to run successfully.

## Related Issue

Addresses #366 

## Motivation and Context

Addresses #366 

## How Has This Been Tested?

Tested in ArcGIS Pro 2.2

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by BobBooth** [comment]
@kgonzago - I pulled from your branch and ran the "Create GRG From Point" tool in the Military Tools.pyt (at C:\Users\[username]\Documents\GitHub\military-tools-geoprocessing-toolbox\Geoprocessing) on a map using WGS84, using an input point feature (feature set tool) and 5x5 100x100 meter grid, 33 degree rotation.

I got:
Start Time: Friday, July 6, 2018 1:49:24 PM
Running script CreateGRGFromPoint...
App environment: ARCGIS_PRO
Creating Fishnet Grid
Sorting the grid for labeling
Adding field for labeling the grid
Numbering the grids
 <built-in function getattr> returned NULL without setting an error
Completed script Create GRG From Point...
 Failed to execute (CreateGRGFromPoint).
Failed at Friday, July 6, 2018 1:49:29 PM (Elapsed Time: 5.05 seconds)

**Comment by kgonzago** [comment]
@BobBooth I tested the fix with several scenarios the past day and with @csmoore's help determined the tool will work in a projected coordinate system. The tool assumes user's will work in a projected coordinate system since all the logic to create a GRG are in meters. This is issue will need to be further discussed with the team. Putting this temporarily on hold.

**Comment by dfoll** [comment]
@topowright do we need this PR anymore, or can we close it? #366 says you have a newer fix

**Comment by topowright** [comment]
Looking closer at issue #366 there are two issues trying to be addressed. The first issue is grid rotation with a web auxiliary sphere projection. This PR fixes this issue. 

The second issue is the tool does not work with any other projection or coordinate system in ArcGIS Pro. That might have been a mistake during the design process. I have opened another issue to capture that fix that is needed.

**Pull request merged**
