### PR TITLE
Updates to LLOS

### PR DESCRIPTION
**Pull request by topowright**
Removed duplicate layers feeding merge for mbg
Removed copy features after los gp tool
corrected calc tool for z values (we no longer have a height filed)

### CODE REVIEW

**Comment by mfunk** [comment]
@topowright Checking it out and there are two things that need to be fixed:

* [ ] The tool is missing the output parameter for the model. In testing I can't tell it where to save my output.

image

In the model either *intermedLOS* or *LLOS(2)* are the candidates, but both probably need a rename to something like *Output Line Of Sight Features*.

image


* [ ] Also seeing that the group box for the output is named *Group (2)*. I know that wasn't what you intended.

* [ ] .... and I'm getting a tool failure....

```
Messages
Start Time: Tue May 17 10:38:39 2016
Failed to execute. Parameters are not valid.
ERROR 000584: Implementation of this Tool's Validate is invalid.
ERROR 000584: Implementation of this Tool's Validate is invalid.
ERROR 000584: Implementation of this Tool's Validate is invalid.
ERROR 000584: Implementation of this Tool's Validate is invalid.
ERROR 000584: Implementation of this Tool's Validate is invalid.
ERROR 000584: Implementation of this Tool's Validate is invalid.
ERROR 000584: Implementation of this Tool's Validate is invalid.
ERROR 000584: Implementation of this Tool's Validate is invalid.
WARNING 000873: Output raster: The workspace C:\Users\matt2542\Documents\ArcGIS\Projects\MyProject13\MyProject13.gdb\ does not exist.
The value is empty.
Failed to execute (LinearLineOfSight).
Failed at Tue May 17 10:38:48 2016 (Elapsed Time: 8.52 seconds)
```

Again looking in the model (and adding values to the relevant input to test validation) the validation stops at **Feature To 3D By Attribute (2)** in *Create Usable Observers* and **Feature To 3D By Attribute** in *Create Usable Targets*.

image

Though this doesn't seem to be what would cause it to fail.

**Comment by mfunk** [comment]
@topowright I think I got the third problem (tool failure) figured out.

The *Output Observer Locations* coming out of *Feature To 3D By Attribute (2)* is being set to:
*C:\Users\<user>\Documents\ArcGIS\Projects\MyProject13\MyProject13.gdb\obs3d*, which doesn't exist (I don't have a MyProject13). If I set it to *%scratchGDB%\obs3d* we are back in business. Until the next one ... in the **Construct Sight Lines** needs to have the *ObsZ* and *TgtZ* field properties removed.

**Comment by topowright** [comment]
@mfunk I have updated the model based on your feedback above.

**Comment by mfunk** [comment]
Merged this one in #75

**Pull request closed without merging**
