### PR TITLE
Update Toolbox : Visibility : Find Local Peaks

### PR DESCRIPTION
**Pull request by pshowalter**
Update Model with Groups
Update documentation
@mfunk @topowright

### CODE REVIEW

**Comment by topowright** [comment]
@pshowalter Being that this was done after my merge request I think it will cause conflicts. @mfunk lets work thru this sometime after scrum.

**Comment by mfunk** [comment]
@topowright I will merge all of the open PRs after scrum.

**Comment by mfunk** [comment]
@pshowalter After I merge @topowright pull request I will pull your changes and merge them into the TBX in dev.

**Comment by mfunk** [comment]
@pshowalter 
In the meantime I've checked this out and the model looks good to me.

**Comment by mfunk** [comment]
Merged this in #48..

**Pull request closed without merging**
