### PR TITLE
add test suite for visibility, include test case for Find Local Peaks

### PR DESCRIPTION
**Pull request by jmccausland**

### CODE REVIEW

**Comment by jmccausland** [comment]
@mfunk please review, advise and merge if ready

**Comment by mfunk** [comment]
Getting some 'errors' running the test in Pro and in Desktop:

```
Testing Find Local Peaks (Pro).
Running tool (Find Local Peaks)
PYTHON ERRORS:
Traceback info:
  File "C:\Users\matt2542\Documents\GitHub\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\FindLocalPeaksTestCase.py", line 83, in test_find_local_peaks
    arcpy.FindLocalPeaks2_ma(self.inputArea, 10, self.inputSurface, self.outputPoints)

Error Info:
'module' object has no attribute 'FindLocalPeaks2_ma'

ArcPy ERRORS:
Start Time: Tue May 17 09:36:36 2016
Succeeded at Tue May 17 09:36:37 2016 (Elapsed Time: 0.43 seconds)

Test success: True
RESULTS =================================================

Number of tests run: 8
Number of errors: 0
Number of failures: 0

END OF TEST =========================================
```

So not sure why it is not finding the tool *FindLocalPeaks2_ma*. But that is probably saying something is wrong and unittest isn't properly capturing it.


Also in the Desktop version we are hitting:

```
Testing Table To Polyline (Desktop).
ArcPy works
Spatial checked out
Testing Find Local Peaks (Desktop).
Running tool (Find Local Peaks)
<string>:1: SyntaxWarning: import * only allowed at module level
Test success: True
RESULTS =================================================

Number of tests run: 8
Number of errors: 0
Number of failures: 0

END OF TEST =========================================
```

This is less concerning but is still a warning.

**Comment by mfunk** [comment]
Looking at it now I see that the tool name is wrong in Desktop.

image


@jmccausland Can you fix this in your pull? The tool Name should be **FindLocalPeaks**, and the toolbox alias should be **mt** not *ma*. This one isn't your fault, but will make the tests for Pro run and make the tools more consistent

**Comment by mfunk** [comment]
@jmccausland Actually can you fix both the Pro and Desktop aliases and make them **mt**?

**Comment by jmccausland** [comment]
@mfunk I'm on it, =)

**Comment by jmccausland** [comment]
@mfunk updated, but I can't find what's causing the 
` <string>:1: SyntaxWarning: import * only allowed at module level `

**Comment by mfunk** [comment]
it is usually an *import * from <lib>* that is in the wrong place. I didn't see it either. Might have to dig for that a bit more.

**Comment by mfunk** [comment]
Looking good. Thanks @jmccausland !!

**Pull request merged**
