### PR TITLE
Add Lowest Points Test Case

### PR DESCRIPTION
**Pull request by jmccausland**
also a missed rename in FindLocalPeaksTestCase

### CODE REVIEW

**Comment by jmccausland** [comment]
@mfunk please review and merge

**Comment by mfunk** [comment]
@jmccausland checking it out now.

**Comment by mfunk** [comment]
@jmccausland So I've shot myself in the foot with this one when I moved to the daily build of Pro 1.3, which now uses a different Python setup and now I'm unable to run the Pro tests. Still working on this one.

**Comment by mfunk** [comment]
Got a workaround to the propy issue and back testing this again...

**Pull request merged**
