### PR TITLE
Updates to RLOS Pro model

### PR DESCRIPTION
**Pull request by topowright**
Updates to RLOS Pro Model

### CODE REVIEW

**Comment by mfunk** [comment]
@topowright checking it out now.

**Comment by mfunk** [comment]
@topowright  Got a few things still..

In ArcMap:
* [ ] the 'visibility' (Observer Visibility) field is still coming out as "2":
image
image

* [ ] The output layer file isn't labeling in the Contents. and seems to be pulling from 'gridcode' and not 'visibility':
image

**Comment by dhagens** [comment]
I'm going to merge this.  The ArcMap model can be fixed in another PR.  Want to get this published and tested.

**Comment by dhagens** [comment]
@topowright @mfunk , should we remove the rlos observers from the test data?  I can run the tool, with warnings, using the LLOS Observers but it fails with the RLOS Observers because of trying to add fields that already exist.

**Comment by mfunk** [comment]
I'd say we just remove the RADIUS2 & OFFSTA fields from the **RLOS_Observers** test features.

**Comment by mfunk** [comment]
@topowright @dhagens 
I'll try to fix some of this stuff in a new PR in an hour or two.

**Pull request merged**
