### PR TITLE
Toolbox fix for Desktop 10.3 and Pro 1.2

### PR DESCRIPTION
**Pull request by mfunk**
Lots of fixes in the commits. Generally needed to make the tools work in:
* ArcGIS 10.3.1 for Desktop
* ArcGIS Pro 1.2

## Description
Too many to really describe here. Had to export tools from Pro 1.4 and *Save As* 10.3 toolbox to get the process started. Then had to go back and fix each model one at a time to get it running on 10.3.1. Some of the problems were originally reported back in April, and fixes done in 10.4+, however this does not help 10.3. For Table To Polygon we had to move to a script tool to get around Model Builder limitations in downstream field picks. This will probably have to be done again for other tools in Conversion toolset. Also had to update for Feature Sets lost in export from Pro (where feature sets aren't functional). This affected Visibility tools. Also some fixes for symbology for tools. Basically at this point the test cases run with exception of anything with Feature Compare. 

## Related Issue
SHOULD fix:
- #135
- #134 
- #130 
- #119 
- #117 
- #110 
- #96 
- #104

Partial fix for:
- #133 

## Motivation and Context
Solves multiple bugs and preps for release.

## How Has This Been Tested?
test framework (utils/tests) is successful with exception of Feature Compare in several tests (where extent and precision differ). Feature Compare is a little too stringent in testing at this time.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by mfunk** [comment]
To summarize what we are seeing with Feature Compare is as follows:

- test_table_to_ellipse_desktop: Feature class extents are different.
- test_table_to_lineofbearing_desktop: Tables have different number of fields (Base: 15, Test: 7)
- test_table_to_point_desktop: Tables have different number of fields (Base: 74, Test: 38)
- test_table_to_polygon_desktop: Spatial References have different XY precision (Base: -400.000000000000, -400.000000000000, 999999999.999999880000, Test: -400.000000000000, -400.000000000000, 11258999068426.238000000000).
- test_radial_line_of_sight_desktop: self.assertEqual(featureCount, expectedFeatures, "Expected %s features, but got %s" % (str(expectedFeatures), str(featureCount)))
AssertionError: Expected 3501 features, but got 155


```
ERROR: 2016-11-15 14:44:05,053 FAILURES ===============================================

test_table_to_ellipse_desktop (conversion_tests.TableToEllipseTestCase.TableToEllipseTestCase)Traceback (most recent call last):
  File "D:\GitHub\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToEllipseTestCase.py", line 83, in test_table_to_ellipse_desktop
    self.assertEqual(identical, "true", "Feature Compare failed: \n %s" % arcpy.GetMessages())
AssertionError: Feature Compare failed: 
 Executing: FeatureCompare D:\GitHub\military-tools-geoprocessing-toolbox\testdata\Results.gdb\ExpectedOutputTableToEllipse D:\GitHub\military-tools-geoprocessing-toolbox\testdata\scratch.gdb\outputEllipses JoinID ALL # "0.000000008983 Unknown" 0.001 0.001 # # NO_CONTINUE_COMPARE #
Start Time: Tue Nov 15 14:37:50 2016
FeatureClass: Feature class extents are different.
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
Succeeded at Tue Nov 15 14:37:50 2016 (Elapsed Time: 0.07 seconds)

..............................................................
test_table_to_lineofbearing_desktop (conversion_tests.TableToLineOfBearingTestCase.TableToLineOfBearingTestCase)Traceback (most recent call last):
  File "D:\GitHub\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToLineOfBearingTestCase.py", line 83, in test_table_to_lineofbearing_desktop
    self.assertEqual(identical, "true", "Feature compare failed: \n %s" % arcpy.GetMessages())
AssertionError: Feature compare failed: 
 Executing: FeatureCompare D:\GitHub\military-tools-geoprocessing-toolbox\testdata\Results.gdb\ExpectedOutputTableToLOB D:\GitHub\military-tools-geoprocessing-toolbox\testdata\scratch.gdb\outputLines OID ALL # "0.000000008983 Unknown" 0.001 0.001 # # NO_CONTINUE_COMPARE #
Start Time: Tue Nov 15 14:38:05 2016
Table: Tables have different number of fields (Base: 15, Test: 7).
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
FeatureClass: Feature class extents are the same.
GeometryDef: GeometryDefs are the same.
Field: Field properties are the same.
Succeeded at Tue Nov 15 14:38:05 2016 (Elapsed Time: 0.06 seconds)

..............................................................
test_table_to_point_desktop (conversion_tests.TableToPointTestCase.TableToPointTestCase)Traceback (most recent call last):
  File "D:\GitHub\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToPointTestCase.py", line 82, in test_table_to_point_desktop
    self.assertEqual(identical, "true", "Feature compare failed: \n %s" % arcpy.GetMessages())
AssertionError: Feature compare failed: 
 Executing: FeatureCompare D:\GitHub\military-tools-geoprocessing-toolbox\testdata\Results.gdb\ExpectedOutputTableToPoint D:\GitHub\military-tools-geoprocessing-toolbox\testdata\scratch.gdb\outputTableToPoint OID ALL # "0.000000008983 Unknown" 0.001 0.001 # # NO_CONTINUE_COMPARE #
Start Time: Tue Nov 15 14:38:18 2016
Table: Tables have different number of fields (Base: 74, Test: 38).
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
FeatureClass: Feature class extents are the same.
GeometryDef: GeometryDefs are the same.
Field: Field properties are the same.
Succeeded at Tue Nov 15 14:38:18 2016 (Elapsed Time: 0.07 seconds)

..............................................................
test_table_to_polyline_desktop (conversion_tests.TableToPolylineTestCase.TableToPolylineTestCase)Traceback (most recent call last):
  File "D:\GitHub\military-tools-geoprocessing-toolbox\utils\test\conversion_tests\TableToPolylineTestCase.py", line 83, in test_table_to_polyline_desktop
    self.assertEqual(identical, "true", "Feature compare failed: \n %s" % arcpy.GetMessages())
AssertionError: Feature compare failed: 
 Executing: FeatureCompare D:\GitHub\military-tools-geoprocessing-toolbox\testdata\Results.gdb\ExpectedOutputTableToPolyline D:\GitHub\military-tools-geoprocessing-toolbox\testdata\scratch.gdb\outputPolylines Shape_Length ALL # "0.000000008983 Unknown" 0.001 0.001 # # NO_CONTINUE_COMPARE #
Start Time: Tue Nov 15 14:38:45 2016
SpatialReference: Spatial References have different XY precision (Base: -400.000000000000, -400.000000000000, 999999999.999999880000, Test: -400.000000000000, -400.000000000000, 11258999068426.238000000000).
FeatureClass: Shape types are the same.
FeatureClass: Feature types are the same.
Table: Table row counts are the same.
FeatureClass: Feature class extents are the same.
GeometryDef: GeometryDefs are the same.
Field: Field properties are the same.
Table: Table row counts are the same.
Succeeded at Tue Nov 15 14:38:45 2016 (Elapsed Time: 0.12 seconds)

```

**Comment by mfunk** [comment]
@csmoore  @topowright  Will either of you be able to review this before the end of the week? Thanks.

**Comment by topowright** [comment]
@ACueva please let me know if you are not going to this and I will set up a machine to test this on 10.3.1

**Comment by ACueva** [comment]
@topowright I haven't started to review this yet.  All yours if you have time to do so.

**Comment by topowright** [comment]
@ACueva Its all yours.

**Comment by jrweakland** [comment]
Merged

**Pull request merged**
