### PR TITLE
add test cases for Add LLOS & RLOS Fields

### PR DESCRIPTION
**Pull request by jmccausland**

### CODE REVIEW

**Comment by jmccausland** [comment]
@mfunk please review and merge

**Comment by mfunk** [comment]
Reviewing it now.

**Comment by mfunk** [comment]
Hey @jmccausland 

Came across a few things in the tests and I'm getting errors that both tools failed to create output:

```
..............................................................
test_add_llos_fields_pro (visibility_tests.AddLLOSFieldsTestCase.AddLLOSFieldsTestCase)Traceback (most recent call last):
  File "D:\GitHub\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\AddLLOSFieldsTestCase.py", line 93, in test_add_llos_fields_pro
    self.assertTrue(arcpy.Exists(self.inputObservers), "Input dataset does not exist")
AssertionError: False is not true : Input dataset does not exist

..............................................................
test_add_rlos_observer_fields_pro (visibility_tests.AddRLOSObserverFieldsTestCase.AddRLOSObserverFieldsTestCase)Traceback (most recent call last):
  File "D:\GitHub\military-tools-geoprocessing-toolbox\utils\test\visibility_tests\AddRLOSObserverFieldsTestCase.py", line 128, in test_add_rlos_observer_fields_pro
    self.assertTrue(arcpy.Exists(self.inputObservers), "Input dataset does not exist")
AssertionError: False is not true : Input dataset does not exist

..............................................................
```

Looking at the tests I think I see some potential issues. For **test_add_llos_fields_pro**:

* [ ] The *inputObservers* dataset is no looking for an *Observers* feature class. Which does not exist in the latest pull from **dev**. It's been renamed **RLOS_Observers**. It should be calling **LLOS_Observers**, and **LLOS_Targets**. These were just changed by Dan this morning, so you can blame him :)

* [ ] Perhaps more importantly we are modifying (adding fields) to the permanent inputObservers features in the repo. The test should probably copy the **LLOS_Observers** and the **LLOS_Targets** to scratch (Configuration.militaryScratchGDB) and then use that as input. If we add fields to scratch it doesn't matter because the *tearDown* should be removing it.

* [ ] Also, we can completely drop the desktop version of the tests as we don't have these tools in the  desktop toolbox and don't have plans to add them.

For **test_add_rlos_observer_fields_pro**:

* [ ] Similar to the LLOS, we should be copying the inputObservers to scratch before we add fields. again this is modifying the source test data in the geodatabase.

* [ ] Here the inputObservers should be using the *RLOS_Observers* features in the input geodatabase.

* [ ] For the assertEquals checking the fields it is going to be difficult to see which field failed without looking at the lines before the actual assert statement. The fail message is generic to all of the asserts. Could we make it that the message says which field was checked for and failed..

```
            fieldList = arcpy.ListFields(self.inputObservers, "RADIUS1")
            fieldCount = len(fieldList)
            self.assertEqual(fieldCount, 1, "Expected a field count of 1 for RADIUS1 field but got %s." % str(fieldCount))
```

* [ ] Just like LLOS we can drop the desktop tests entirely.

* [ ] Also don't forget to add a line to the file *history* in the header!!! Get some credit for starting the file! :)

**Comment by jmccausland** [comment]
All updated

**Comment by mfunk** [comment]
Thanks @jmccausland reviewing it again.

**Comment by mfunk** [comment]
@jmccausland the new tests look good and run nicely. Please delete the *jm-add-add-llos-fields-test-case* branch.

**Pull request merged**
