### PR TITLE
Add Radial Line of Sight and Range Tool

### PR DESCRIPTION
**Pull request by csmoore**
## Description

1. Add RadialLineOfSightAndRange tool and test case(s)
Action from viewshed/RLOS meeting to add/begin process of analyzing RLOS tools and potentially moving GP tool from:
https://github.com/Esri/solutions-webappbuilder-widgets/tree/dev/Visibility/gpservices here
2. Renamed mispelled tool/script: RadiaLineOfSight -> Radia**l**LineOfSight
3. Added layer files, modified RLOS.lyr to add additional labels

## How Has This Been Tested?

1. Tested extensively in previous repo/project (AirC2)
2. Tested extensively during last sprint 
3. Unit test cases added with PR

## Screenshots (if appropriate):

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.`*`
- [ ] I have updated the documentation accordingly.`*`
- [X] I have read the **CONTRIBUTING** document.

`*` Pending further investigation by the team into 2 RLOS tools
 
FYI (Meeting attendees): @adgiles @topowright @mfunk @NatalieCampos @BobBooth @pHill5136 @kgonzago @nfeuerstein @lfunkhouser

### CODE REVIEW

**Comment by csmoore** [comment]
I did do on 10.4, I'll install 10.3 on a VM and make the change (a lovely benefit of binary compatibility), you should be able to test on Pro 1.4 (assuming that is the correct version) - sorry about that (I didn't know 10.4/10.3 weren't binary compatible)

**Comment by mfunk** [comment]
Just go from your 10.4 machine and "SAVE AS" >> 10.3. Should save you some install time. :)

**Comment by csmoore** [comment]
OK - de-updated/downgraded this to 10.3 - this is ready for review again. 

Important/Note: this should probably **not** be merged until after the 1.1 Release/branch is created but feel free to review at your convenience.

**Comment by csmoore** [comment]
The 1.1 release has been created so this is ready to review/merge at your convenience (and hopefully before someone makes another toolbox change).

**Comment by mfunk** [comment]
@csmoore Checking now....

**Pull request merged**
