### PR TITLE
Update params in RLOS

### PR DESCRIPTION
**Pull request by BobBooth**
Updates params in RLOS from erroneous 'param_3" to correct "param_7"

This changes the param_3s that should be param_7s back.
## Description
fixes blunder
## Related Issue
https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/334
https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/331

## Motivation and Context
Tool did not have correct parameters, failed.

## How Has This Been Tested?
Tested locally. Tool has radius of observer parameter and runs, rather than failing.
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by BobBooth** [comment]
@dfoll - this fixes the RLOS issue I found while doing the cucumber test for RLOS.

**Comment by BobBooth** [comment]
@kgonzago - found another case of this problem, fixed in this PR.

**Comment by BobBooth** [comment]
Oops, sorry, I usually remember to exclude the GDB changes.

**Comment by csmoore** [comment]
Closing - change made in #335

**Pull request closed without merging**
