### PR TITLE
Addresses #358

### PR DESCRIPTION
**Pull request by kgonzago**
Sending a string to arcpy.Exists() method instead of a GP object.
## Description

arcpy.Exists() was throwing an error when executing on an input parameter that is a GP object.

## Related Issue

Addresses #358 

## Motivation and Context

Addresses #358 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by csmoore** [comment]
Testing now

**Comment by csmoore** [comment]
Tests good with change (below):

The only question I have for the team @kgonzago @topowright @dfoll @BobBooth is if this also occurs in ArcMap and fix should be made in that forked tree also: https://github.com/Esri/military-tools-geoprocessing-toolbox/blob/dev/Geoprocessing/scripts/GRGUtilities.py

image

**Comment by dfoll** [comment]
we actually found it in arcmap first and saw it also happening in pro

**Comment by topowright** [comment]
@csmoore we are not seeing this problem in the conda package. Merging now.

**Pull request merged**
