### PR TITLE
Update LLOS_InputObserversGDB.lyr to include feature template

### PR DESCRIPTION
**Pull request by BobBooth**
The "LLOS_InputObserversGDB.lyr" is updated to include a feature template. This fixes an issue with the LLOS and RLOS tools in Pro 2.3 not giving a feature template when the pencil button is clicked.

### CODE REVIEW

**Comment by BobBooth** [comment]
@csmoore - I updated this LYR file to have a feature template (in ArcMap 10.3.1).  When I tested locally, this resolved the issue with RLOS and LLOS not giving a point feature for featureset input.
Please review and merge.
@dfoll

**Comment by BobBooth** [comment]
Seeing slightly strange behavior when I copy the repo to another location and re-test. The LLOS Input Observers "pencil" icon now gives me a dropdown list of point, line, and polygon options.  When I click the point option, an input point featureset is created.
The Targets input feature set simply opens the point featureset input for the targets with no dropdown.
Also, the input location is symbolized with a "pin" symbol rather than a circle, as I had expected.
image

**Comment by BobBooth** [comment]
OK, with latest commit I am seeing the correct behavior.
@dfoll - please review. Thanks!

**Comment by csmoore** [comment]
@BobBooth - unfortunately, this version didn't work for me - perhaps we may need to switch these to lyrx files when running in Pro

image

**Comment by dfoll** [comment]
unassigning myself until there is an approval on this.... don't to forget about my own assignment because i left it sitting

**Comment by BobBooth** [comment]
@csmoore @dfoll  please retest using the updated LYR file from my latest PR.

**Comment by csmoore** [comment]
This on worked for me on 2.3.15512

image

image

**Pull request merged**
